name: numerus
description: Dart extensions for translating integers to Roman numerals and Roman numeral strings to integers.
version: 2.3.0
homepage: https://github.com/greymouser/dart-numerus

environment:
  sdk: ^3.0.0 # Dart version - 3.0.0 to 4.0.0

dependencies:
  characters: ^1.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.21.0
