name: numerus
description: Dart extensions for translating integers to Roman numerals and Roman numeral strings to integers.
version: 2.0.0
homepage: https://github.com/greymouser/dart-numerus

environment:
  sdk: '>=2.16.0 <3.0.0' # Dart version

dependencies:
  characters: ^1.2.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
