name: numerus
description: Dart extensions for translating integers to Roman numerals and Roman numerals strings to integers.
version: 1.1.1
homepage: https://github.com/greymouser/dart-numerus

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
