name: numerus
description: Dart extensions for translating integers to Roman numerals and Roman numerals strings to integers.
version: 1.1.0
homepage: https://github.com/greymouser/dart-numerus

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.16.0-nullsafety.12
  test_coverage: ^0.5.0
